In [0]:
import torch
from torch.nn import Linear

In [0]:
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

In [0]:
def forward(x):
  y = w * x + b
  return y

In [13]:
x = torch.tensor([[4],[7]])
forward(x)

tensor([[13],
        [22]], grad_fn=<AddBackward0>)

In [15]:
torch.manual_seed(1)

model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [20]:
x = torch.tensor([[2.0], [3.3]])
print(model(x))

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward>)
