In [1]:
import numpy as np

In [14]:
x = np.arange(18)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [3]:
x[2:7]

array([3, 4, 5, 6, 7])

In [6]:
x[:7:2]

array([1, 3, 5, 7])

In [17]:
print(x.reshape(2,3,3))
print(x.reshape(3,3,2))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
