In [3]:
import numpy as np

x = np.arange(18).reshape(3,2,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [11]:
x[1,:2,:3:2]

array([[ 6,  8],
       [ 9, 11]])

In [13]:
comaprison_operation = x >5
print(comaprison_operation)

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]


In [14]:
x[x>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [15]:
x.max()

17

In [16]:
x.min()

0

In [20]:
# A view of original array
raveled_array = x.ravel()
print(raveled_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [21]:
# returns a new array
flattened_Array = x.flatten()
print(flattened_Array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [28]:
y = np.arange(9)
y.shape = [3,3]
print(y)
print(y.transpose())
print(y.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [29]:
print(np.resize(y, (6,6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [34]:
print(np.zeros((3,2), dtype=int))


[[0 0]
 [0 0]
 [0 0]]


In [35]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [39]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
np.random.rand(4,4)

array([[0.75409974, 0.47244634, 0.1303902 , 0.20214624],
       [0.66806368, 0.02546736, 0.64091069, 0.50382271],
       [0.05121801, 0.43788282, 0.71638555, 0.65965937],
       [0.75584407, 0.43515663, 0.02248561, 0.79747909]])

In [48]:
matA = np.array([0,3,5,5,5,2]).reshape(2,3)
matA

array([[0, 3, 5],
       [5, 5, 2]])

In [49]:
matB = np.array([3,4,3, -2,4,-2]).reshape(3,2)
matB

array([[ 3,  4],
       [ 3, -2],
       [ 4, -2]])

In [53]:
# Can only be use when using np.matrix
matA * matB

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [54]:
product = np.matmul(matA, matB)
product

array([[ 29, -16],
       [ 38,   6]])

In [55]:
matA @ matB

array([[ 29, -16],
       [ 38,   6]])