In [1]:
list_two = list(range(1,4))
list_three = list(range(1,4))

list_sum = []

In [2]:
for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] **3
    list_sum.append(list_two[index] + list_three[index])
list_sum

[2, 12, 36]

In [20]:
import numpy as np

array_two = np.arange(1,4)
array_three = np. arange(1,4)

array_two = array_two ** 2
array_three = array_three ** 3

array_sum = array_two + array_three
print(array_sum)

[ 2 12 36]


In [21]:
sample_array = np.array([1,2,3])

In [22]:
print(np.power(sample_array,2))

[1 4 9]


In [23]:
print(np.negative(sample_array))

[-1 -2 -3]


In [24]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229])

In [25]:
np.tan(sample_array)

array([ 1.55740772, -2.18503986, -0.14254654])

In [26]:
np.sin(sample_array)

array([0.84147098, 0.90929743, 0.14112001])

In [58]:
x = np.arange(3)
y = np.arange(3,6)
z = np.arange(6,9)

multi_array = np.array([x, y, z], dtype = np.int16)
print(multi_array)
print('{} is the shape'.format(multi_array.shape))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3) is the shape


In [59]:
print(multi_array[2][2])
print(multi_array.dtype)

8
int16


In [45]:
w = np.linspace(1, 30, 5)
print(w)

[ 1.    8.25 15.5  22.75 30.  ]


In [46]:
b = np.arange(1,30, 5)
print(b)

[ 1  6 11 16 21 26]
