In [0]:
import torch

In [3]:
x = torch.arange(18).view([3,2,3])
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [10]:
x[1,0:2,0:3]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [11]:
x[1,]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [12]:
mat_A = torch.tensor([0,3,5,5,5,2]).view([2,3])
mat_B = torch.tensor([3,4,3,-2,4,-2]).view([3,2])

print(mat_A)
print(mat_B)

tensor([[0, 3, 5],
        [5, 5, 2]])
tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])


In [14]:
torch.matmul(mat_A, mat_B)

tensor([[ 29, -16],
        [ 38,   6]])

In [15]:
mat_A @ mat_B

tensor([[ 29, -16],
        [ 38,   6]])

In [17]:
x = torch.tensor(2.0, requires_grad=True)
y = 9 *x**4 + 2*x**3 + 3*x**2 + 6*x + 1

y.backward()
x.grad

tensor(330.)

In [20]:
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(2.0, requires_grad=True)
y = x**2 + z**3
y.backward()
print(x.grad)
print(z.grad)

tensor(2.)
tensor(12.)
