In [1]:
import numpy as np

In [3]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [4]:
y = np.arange(4,8).reshape(2,2)
y

array([[4, 5],
       [6, 7]])

In [6]:
z = np.hstack([x,y])
z

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [7]:
w = np.vstack([x,y])
w

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [10]:
np.concatenate((x,y), axis=1)

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [11]:
np.concatenate((x,y), axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [12]:
z == np.concatenate((x,y), axis=1)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [16]:
depth_stack = np.dstack((x,y))
depth_stack

array([[[0, 4],
        [1, 5]],

       [[2, 6],
        [3, 7]]])

In [19]:
column_stack = np.column_stack((x,y))
print(column_stack)

[[0 1 4 5]
 [2 3 6 7]]


In [22]:
z == column_stack

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
np.row_stack((x,y))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])