In [1]:
!pip2 install torch

In [18]:
import torch
import numpy as np

v = torch.tensor([1,2,3,4,5,6])
v.dtype

torch.int64

In [19]:
v[0:]

tensor([1, 2, 3, 4, 5, 6])

In [20]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f.dtype)
print(f.size())

torch.float32
torch.Size([6])


In [21]:
v.view(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [22]:
v.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [23]:
v.view(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [0]:
a = np.array([1,2,3,4,5])

In [28]:
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [29]:
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]
